[platformio]
src_dir = firmware/src
include_dir = firmware/include
test_dir = firmware/test

[env:esp32-wrover-radio]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter =
  +<*>
  -<sim_wokwi.cpp>
build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DA2DP_I2S_AUDIOTOOLS=0
lib_deps =
  https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.0
  https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.10
  bblanchon/ArduinoJson@^7.0.0
  olikraus/U8g2@^2.36.0
  mathertel/RotaryEncoder@^1.5.3

[env:esp32-wokwi-sim]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts =
  post:firmware/scripts/merge_wokwi_firmware.py
build_src_filter =
  -<*>
  +<radio_controller.cpp>
  +<sim_wokwi.cpp>
lib_deps =
  olikraus/U8g2@^2.36.0
  mathertel/RotaryEncoder@^1.5.3
